/*******************************************************************************
 * File Name: project.h
 * PSoC Creator  3.1 SP3
 *
 *  Description:
 *  This file is automatically generated by PSoC Creator and should not 
 *  be edited by hand.
 *
 *
 ********************************************************************************
 * Copyright 2008-2013, Cypress Semiconductor Corporation.  All rights reserved.
 * You may use this file only in accordance with the license, terms, conditions, 
 * disclaimers, and limitations in the end user license agreement accompanying 
 * the software package with which this file was provided.
 ********************************************************************************/

#include <cyfitter_cfg.h>
#include <cydevice.h>
#include <cydevice_trm.h>
#include <cyfitter.h>
#include <cydisabledsheets.h>
#include <RotarySensor_V_aliases.h>
#include <RotarySensor_V.h>
#include <RotarySensor_W_aliases.h>
#include <RotarySensor_W.h>
#include <RotarySensor_U_aliases.h>
#include <RotarySensor_U.h>
#include <ADC.h>
#include <Current_HB1_aliases.h>
#include <Current_HB1.h>
#include <Rx_1_aliases.h>
#include <Rx_1.h>
#include <Door_Motor_Speed.h>
#include <Door_GO.h>
#include <Current_HB3_aliases.h>
#include <Current_HB3.h>
#include <Current_HB2_aliases.h>
#include <Current_HB2.h>
#include <Zacc_aliases.h>
#include <Zacc.h>
#include <Yacc_aliases.h>
#include <Yacc.h>
#include <Xacc_aliases.h>
#include <Xacc.h>
#include <RotarySensor_SSI_DIO_aliases.h>
#include <RotarySensor_SSI_DIO.h>
#include <RotarySensor_SSI_CLK_aliases.h>
#include <RotarySensor_SSI_CLK.h>
#include <RotarySensor_Ncc_aliases.h>
#include <RotarySensor_Ncc.h>
#include <StartStop.h>
#include <Door_Bumper_Port_aliases.h>
#include <Door_Bumper_Port.h>
#include <Door_Step_aliases.h>
#include <Door_Step.h>
#include <Door_Step_Dist.h>
#include <CAN_BY_aliases.h>
#include <CAN_BY.h>
#include <CAN_1.h>
#include <Tx_1_aliases.h>
#include <Tx_1.h>
#include <PositionCounter.h>
#include <Clock_4.h>
#include <Rotary_PWM_aliases.h>
#include <Rotary_PWM.h>
#include <HB1_1_aliases.h>
#include <HB1_1.h>
#include <HB2_1_aliases.h>
#include <HB2_1.h>
#include <HB3_1_aliases.h>
#include <HB3_1.h>
#include <HB1_En_1_aliases.h>
#include <HB1_En_1.h>
#include <HB2_En_1_aliases.h>
#include <HB2_En_1.h>
#include <HB3_En_1_aliases.h>
#include <HB3_En_1.h>
#include <PWM.h>
#include <Clock_1.h>
#include <Clock_5.h>
#include <isr_SSI_Read.h>
#include <isr_position.h>
#include <SSI_Enable.h>
#include <Clock_2.h>
#include <Clock_3.h>
#include <Em_EEPROM_1.h>
#include <isr_ADC.h>
#include <Clock_6.h>
#include <Clock_7.h>
#include <isr_SSI_Write.h>
#include <PhaseControl.h>
#include <ControlMode.h>
#include <Door_Bumper_ISR.h>
#include <Door_Power.h>
#include <Door_Clock.h>
#include <Door_StepSizeA_aliases.h>
#include <Door_StepSizeA.h>
#include <Door_StepSizeB_aliases.h>
#include <Door_StepSizeB.h>
#include <Door_Direction_aliases.h>
#include <Door_Direction.h>
#include <Door_Enable_aliases.h>
#include <Door_Enable.h>
#include <Door_CurrentRef_aliases.h>
#include <Door_CurrentRef.h>
#include <ADC_SAR.h>
#include <ADC_TempBuf_dma.h>
#include <ADC_FinalBuf_dma.h>
#include <ADC_IRQ.h>
#include <core_cm3_psoc5.h>
#include <core_cm3.h>
#include <CyDmac.h>
#include <CyFlash.h>
#include <CyLib.h>
#include <cypins.h>
#include <cyPm.h>
#include <CySpc.h>
#include <cytypes.h>
#include <core_cmFunc.h>
#include <core_cmInstr.h>

/*[]*/

